### ISSUE TITLE
OCLP shows "No patches required"

### ISSUE THREAD

**Issue by KrishEnacton** [Edwardwich/BCM-WIFI-Sonoma#1]
I have done all the steps but when I try to do "post-install root patch" it shows "No patches required"

I have Intel AC 7260 wifi-bluetooth card

Ref: 
![image](https://github.com/Edwardwich/BCM-WIFI-Sonoma/assets/77377186/27721ce9-96e7-469f-afdc-d896916680a0)

**Comment by Edwardwich** [comment]
its fir bam wifi u have intel 
use heli port app and itlwm.kext 
https://github.com/OpenIntelWireless/itlwm/releases
https://github.com/OpenIntelWireless/HeliPort
https://github.com/OpenIntelWireless/IntelBluetoothFirmware
