### ISSUE TITLE
compile_oclp.sh error when python is installed by homebrew

### ISSUE THREAD

**Issue by perez987** [Edwardwich/BCM-WIFI-Sonoma#3]
Good night. I get an error when `compile_oclp.sh` runs these python related lines:

 ```
pip3 install -r requirements.txt
 sudo ./Build-Project.command
 python3 ./OpenCore-Patcher-GUI.command
```

Since python is installed by homebrew, I get this error:

```
error: externally-managed-environment
× This environment is externally managed
```

And I can't run the whole script.

---

Apart from this, I think that the code

```
# Change directory to the extracted folder
cd OpenCore-Legacy-Patcher-sequoia-development
```

has to be changed to

```
# Change directory to the extracted folder
#cd OpenCore-Legacy-Patcher-sequoia-main
```

since the folder that is created on the Desktop is called `OpenCore-Legacy-Patcher-main`.

**Comment by Edwardwich** [comment]
TNX for the report 
now Try this :
[compile_oclp.sh.zip](https://github.com/user-attachments/files/17187795/compile_oclp.sh.zip)

**Comment by perez987** [comment]
@Edwardwich 
Thanks. Python installed by brew and the command to cd to the folder in Desktop have been fixed.
Now the task progresses until this block

```
Generating DMG...
DMG generation complete
Downloading required resources...
- Downloading Universal-Binaries.dmg...
```

Where I get an error LibreSSL related:

```
ERROR:root:Subprocess failed.
ERROR:root:    Command: ['/usr/bin/curl', '-LO', 'https://github.com/dortania/PatcherSupportPkg/releases/download/1.8.3/Universal-Binaries.dmg']
...
ERROR:root:        curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443 
```

I guess the program is looking for LibreSSL and it doesn't find it because I had OpenSSL instead. But after installing LibreSSL with brew, this error has also been fixed.

---

After fixing the error mentioned above, the program progresses to this point:

```
Generating OpenCore-Patcher.app
ERROR:root:Subprocess failed.
ERROR:root:    Command: ['/Users/yo/Desktop/OpenCore-Legacy-Patcher-main/venv/bin/python3', '-m', 'PyInstaller', './OpenCore-Patcher-GUI.spec', '--noconfirm']
ERROR:root:    Return Code: 1
ERROR:root:    Standard Output:
ERROR:root:        None
ERROR:root:    Standard Error:
ERROR:root:        2 DEPRECATION: Running PyInstaller as root is not necessary nor sensible. Do not use PyInstaller with sudo. PyInstaller 7.0 will block this.
ERROR:root:        105 INFO: PyInstaller: 6.10.0, contrib hooks: 2024.8
ERROR:root:        106 INFO: Python: 3.12.6
ERROR:root:        191 INFO: Platform: macOS-15.0-x86_64-i386-64bit
ERROR:root:        191 INFO: Python environment: /Users/yo/Desktop/OpenCore-Legacy-Patcher-main/venv
ERROR:root:        469 INFO: Module search paths (PYTHONPATH):
... (followed by many ERROR:root lines)
```

**Comment by Edwardwich** [comment]
Ok now try this 
[compile_oclp.sh.zip](https://github.com/user-attachments/files/17203920/compile_oclp.sh.zip)

**Comment by perez987** [comment]
@Edwardwich 
First, thanks for your effort.
Tried latest script, now I go until:

```
# Run the build command without sudo
echo "Generating OpenCore-Patcher.app..."
python3 -m PyInstaller ./OpenCore-Patcher-GUI.spec --noconfirm || { echo "Error: Failed to generate OpenCore-Patcher.app."; exit 1; }
```

The output is:

```
Generating OpenCore-Patcher.app...
122 INFO: PyInstaller: 6.10.0, contrib hooks: 2024.8
123 INFO: Python: 3.12.6
211 INFO: Platform: macOS-15.0-x86_64-i386-64bit
211 INFO: Python environment: /Users/yo/Desktop/OpenCore-Legacy-Patcher-main/venv
703 INFO: Module search paths (PYTHONPATH):
['/Users/yo/Desktop/OpenCore-Legacy-Patcher-main',
 '/usr/local/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python312.zip',
 '/usr/local/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12',
 '/usr/local/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/lib-dynload',
 '/Users/yo/Desktop/OpenCore-Legacy-Patcher-main/venv/lib/python3.12/site-packages',
 '/usr/local/opt/python-tk@3.12/libexec',
 '/Users/yo/Desktop/OpenCore-Legacy-Patcher-main/venv/lib/python3.12/site-packages/setuptools/_vendor',
 '/Users/yo/Desktop/OpenCore-Legacy-Patcher-main',
 '/Users/yo/Desktop/OpenCore-Legacy-Patcher-main']
992 INFO: Appending 'datas' from .spec
Unable to find '/Users/yo/Desktop/OpenCore-Legacy-Patcher-main/payloads.dmg' when adding binary and data files.
Error: Failed to generate OpenCore-Patcher.app.
```

**Comment by Edwardwich** [comment]
@perez987 now try I think fully work :
[compile_oclp.sh.zip](https://github.com/user-attachments/files/17212465/compile_oclp.sh.zip)
![Screenshot 2024-10-01 at 19 15 56](https://github.com/user-attachments/assets/d205389b-0bd1-4c28-91a1-fcee3393db1e)

**Comment by Edwardwich** [comment]
now I run scripts agin 
![Screenshot 2024-10-01 at 19 37 07](https://github.com/user-attachments/assets/07a9efdb-2fe8-4f41-94c7-91fd0d2c40a6)
and seen this error scripts work with out sudo ./Build-Project.command

**Comment by perez987** [comment]
@Edwardwich 
Thinking of those who use Homebrew, you have been fixing issues. Very useful the LibreSSL check and installation if it does not exist.
The last script works fine until `Generating OpenCore-Patcher.app`.
Then the `ERROR:root:` lines start, which I attach in a separate file for better readability.
These errors are related to Build-Project.command, it's a OCLP file so I guess that it doesn't mean new issues in your script. Maybe it has to do with my system.
Thanks anyway.

[ERROR-root.txt](https://github.com/user-attachments/files/17216713/ERROR-root.txt)

**Comment by Edwardwich** [comment]
@perez987 can u try this scripts with python3.10 ?
and  can u create issues in oclp repo and refer to my project ?
only when remove this line able to run oclp app:
![Screenshot 2024-10-02 at 04 44 49](https://github.com/user-attachments/assets/61c17cd0-6152-4cdd-a68f-08908c83d063)

**Comment by perez987** [comment]
@Edwardwich 
I've tried it with Python3.10 and I get the same error with `Generating OpenCore-Patcher.app`.

I've even tried to compile OLCP from source without your script, following the instructions from the devs, and I still get the same error in the same place.

There seems to be an issue (at least on some systems) with the `Build-Project.command `script.

It's not possible to create OCLP issues for a while now, devs have closed this system which is restricted to the devs themselves. It's no longer open to the public.

I'll try to find out more but for now I can't tell you much more.

Thanks for everything you've done so far.

**Comment by Edwardwich** [comment]
TNX man I keep open this issues if u fount way to fix tell me here

**Comment by Edwardwich** [comment]
@perez987 finally I fix that now run scripts and enjoy
![Screenshot 2024-10-09 at 02 43 04](https://github.com/user-attachments/assets/30917fcf-7e6f-4e13-a3aa-f36c02bda2c6)

**Comment by perez987** [comment]
@Edwardwich 
Thank you, I'll try and comment.

**Comment by perez987** [comment]
@Edwardwich 
Nothing to do. I can't compile the app. All works fine until `OpenCore-Patcher-GUI` phase, the app runs fine from Terminal, but `Build-Project.command` phase fails, no matter what i do.
It's not really important for me, because I almost never compile OCLP but use the app generated by the devs.
There is something that I still don't know what it is that prevents me from finishing the task on my system.
Anyway, a lot of thanks for your effort.
I attach the Terminal output in case it can be useful.

[compile_oclp.sh -output.txt](https://github.com/user-attachments/files/17318880/compile_oclp.sh.-output.txt)

**Comment by Edwardwich** [comment]
> @Edwardwich Nothing to do. I can't compile the app. All works fine until `OpenCore-Patcher-GUI` phase, the app runs fine from Terminal, but `Build-Project.command` phase fails, no matter what i do. It's not really important for me, because I almost never compile OCLP but use the app generated by the devs. There is something that I still don't know what it is that prevents me from finishing the task on my system. Anyway, a lot of thanks for your effort. I attach the Terminal output in case it can be useful.
> 
> [compile_oclp.sh -output.txt](https://github.com/user-attachments/files/17318880/compile_oclp.sh.-output.txt)

I try to compile oclp app but I thing we need somting like key to fully compile just app
u can try fork oclp repo and work on it for make .app I doesn't find any way to just compile the app

**Comment by perez987** [comment]
@Edwardwich
Last attempt: I've completely deleted homebrew, manually installed Python 3.10, downloaded the OLCP source code, followed the instructions from the devs on [SOURCE.md](https://github.com/dortania/OpenCore-Legacy-Patcher/blob/main/SOURCE.md) and have been unsuccessful, errors are thrown when creating OpenCore-Patcher-GUI or creating the app.
I don't know if I have the skills to work on the OCLP code but I'll take a look and let you know if I can figure out anything.
I'm closing the issue for now.
Thanks again.
